"""add basketball support

Revision ID: 5958beee4715
Revises: 6cdd6560db11
Create Date: 2026-09-19 04:47:35.899047+00:00

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5958beee4715'
down_revision: Union[str, None] = '6cdd6560db11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sporttype_enum = sa.Enum('football', 'basketball', name='sporttype')
    sporttype_enum.create(op.get_bind())
    op.add_column('tournaments', sa.Column('sport', sporttype_enum, nullable=False, server_default='football'))
    op.alter_column('tournaments', 'sport', server_default=None)

    # Add basketball positions to playerposition enum
    with op.get_context().autocommit_block():
        op.execute("ALTER TYPE playerposition ADD VALUE IF NOT EXISTS 'point_guard'")
        op.execute("ALTER TYPE playerposition ADD VALUE IF NOT EXISTS 'shooting_guard'")
        op.execute("ALTER TYPE playerposition ADD VALUE IF NOT EXISTS 'small_forward'")
        op.execute("ALTER TYPE playerposition ADD VALUE IF NOT EXISTS 'power_forward'")
        op.execute("ALTER TYPE playerposition ADD VALUE IF NOT EXISTS 'center'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tournaments', 'sport')
    sporttype_enum = sa.Enum('football', 'basketball', name='sporttype')
    sporttype_enum.drop(op.get_bind())
    # Note: removing enum values is not supported in postgres, so we don't drop playerposition values
    # ### end Alembic commands ###
