"""add_dni_to_players_and_delegate_to_teams

Revision ID: 6cdd6560db11
Revises: 001
Create Date: 2026-08-27 21:50:58.452061+00:00

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6cdd6560db11'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('dni', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False))
    op.create_index(op.f('ix_players_dni'), 'players', ['dni'], unique=False)
    op.add_column('teams', sa.Column('delegate_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False))
    op.add_column('teams', sa.Column('delegate_phone', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teams', 'delegate_phone')
    op.drop_column('teams', 'delegate_name')
    op.drop_index(op.f('ix_players_dni'), table_name='players')
    op.drop_column('players', 'dni')
    # ### end Alembic commands ###
